version: "3"
services:
    htx_api:
        build:
            context: .
            dockerfile: ./Dockerfile
        env_file:
            - ./.env
        environment:
            - DB_URI=mongodb://mongo:27017/farm
        volumes: 
            - ".:/usr/src/htx/app"
        restart: always
        ports:
            - "3001:3001"
        links:
            - mongo
    mongo:
        restart: always
        container_name: htx_db
        image: mongo:4.2
        ports:
            - "27017:27017"